language: python
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest
  - coverage run --source pyvid -m pytest
  - coverage report
after_success:
  - coveralls
