language: python
os:
  - linux
python:
  - "3.6"
  - "3.7-dev"
sudo: required
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - ffmpeg -hwaccels
install:
  - pip install -r requirements.txt
script:
  - python -m pytest
  - coverage run --source pyvid -m pytest
  - coverage report
after_success:
  - coveralls
