language: python
os:
  - linux
python:
  - "3.6"
sudo: required
before_install:
  - sudo apt install software-properties-common build-essential
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
  - ffmpeg -hwaccels
  - pip install poetry
install:
  - poetry install
script:
  - poetry run coverage run --source pyvid -m pytest
  - poetry run coverage report
after_success:
  - coveralls
