language: python
os:
  - linux
python:
  - "3.6"
  - "3.7-dev"
sudo: required
before_install:
  - sudo apt install software-properties-common
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg
  - ffmpeg -hwaccels
install:
  - pip install -r requirements.txt
script:
  - coverage run --source pyvid -m pytest
  - coverage report
after_success:
  - coveralls
