language: python
os:
  - linux
python:
  - "3.6"
sudo: required
before_install:
  - sudo apt install software-properties-common build-essential -y
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
  - sudo apt update
  - sudo apt install libavcodec58 libavdevice58 libavfilter7 libavformat58 -y
  - sudo apt install ffmpeg -y
  - ffmpeg -hwaccels
  - pip install poetry
install:
  - poetry install
script:
  - poetry run coverage run --source pyvid -m pytest
  - poetry run coverage report
after_success:
  - coveralls
