[tool.poetry]
name = 'pyvid'
version = '0.0.3'
description = "Video conversion utility"

authors = [
    "jdxt <jytrn@protonmail.com>"
]

readme = 'README.md'

repository = 'https://github.com/0jdxt/pyvid'
homepage = 'https://github.com/0jdxt/pyvid'

keywords = ['video', 'conversion', 'tools']

[tool.poetry.dev-dependencies]
pytest = "^3.8"
pytest-cov = "^2.6"
prospector = "^1.1"
mypy = "^0.630.0"

[tool.poetry.dependencies]
ffmpeg-python = "^0.1.16"
click = "^7.0"
"hurry.filesize" = "^0.9.0"
click-spinner = "^0.1.8"

[tool.poetry.scripts]
pyvid = "pyvid:main"
